# Remove theme
theme: minima
title: Programming 1 @ KU
description: Intro to programming using Java
exclude: [bin, misc, Gemfile, Gemfile.lock]
# Use Git's markdown syntax
markdown: kramdown
kramdown:
    auto_ids: true

# Google Analytics Tracking Number included by _includes/google_analytics.html
site.google_analytics: "UA-104768257-1"
