# Remove theme
theme: minima
title: Programming 1
description: Intro to programming using Java
exclude: [bin, misc, Gemfile, Gemfile.lock]
# Use Git's markdown syntax
markdown: kramdown
kramdown:
    auto_ids: true

# Google Analytics Tracking Number included in _includes/google_analytics.html
google_analytics: "UA-104768257-1"
